### PR TITLE
Swapped dps[3] and dps[4] in htotal calculations

### PR DESCRIPTION
**Pull request by christopheramazur**

### CODE REVIEW

**Comment by christopheramazur** [comment]
```
    var dtotal = (((dps[1].y - dps[0].y + dps[3].y) / (to - dps[2].y)) * 100);
```

//                                   v              v swapped
        var htotal = (((dps[3].y - dps[4].y + dps[0].y) / (to - dps[2].y)) \* 100);

**Comment by Khalid-Nowaf** [comment]
thanks @christopheramazur

**Comment by christopheramazur** [comment]
No problem! I thought the example was great: clear, concise, easy to
follow, good feedback and results. Good job :)

**Comment by christopheramazur** [comment]
Hey Khalid,

I left in a rush but should have stayed to see what you wanted -- my class
wasn't til 130 and I didn't see the time. If you need help with anything
don't hesitate to let me know!

Regards,

Chris Mazur

**Pull request merged**
